# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

colMin <- function(X) {
    .Call('SFtools_colMin', PACKAGE = 'SFtools', X)
}

measr_cpp <- function(x) {
    .Call('SFtools_measr_cpp', PACKAGE = 'SFtools', x)
}

measr_ff <- function(x) {
    .Call('SFtools_measr_ff', PACKAGE = 'SFtools', x)
}

CPP_get_openmp_threads <- function() {
    .Call('SFtools_CPP_get_openmp_threads', PACKAGE = 'SFtools')
}

CPP_set_openmp_threads <- function(n) {
    invisible(.Call('SFtools_CPP_set_openmp_threads', PACKAGE = 'SFtools', n))
}

